[package]
name = "ar-mintin"
version = "0.2.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0"
json = "0.12"
crossterm = "0.23"
rand = "0.8"
clap = { version = "3.1", features = ["derive"] }
ctrlc = "3.2"
